### ISSUE TITLE
4.0.0-beta.1现在能用吗？

### ISSUE THREAD

**Issue by billsking** [dotnetcore/Natasha#110]
我试了，没有NatashaInitializer.InitializeAndPreheating();方法。   NDomain也没有。这个版本现在是什么情况了呢？

**Comment by NMSAzulX** [comment]
@billsking 4.0 bata版本目前是新 API, 文档正在补充中. 大概这周发布.

**Comment by NMSAzulX** [comment]
@billsking 最新版已发布。

**Comment by squirrelfeng** [comment]
请问文档中的HelloWorld是不是没有更新？
比如sharpBuilder.UseFileCompile() 等在4.0中怎么使用呢？谢谢！
