### ISSUE TITLE
注册时提示：应输入标识符

### ISSUE THREAD

**Issue by hyzx86** [dotnetcore/Natasha#126]
Hi 张大帅，

Natasha 在组件中注册时爆了个错误~ 提示： “应输入标识符”

Natasha版本：4.0.0-beta.1
.net 6.0
项目：OrchardCore

![image](https://user-images.githubusercontent.com/15613121/162036987-d0c7a051-003c-4d27-b59b-0366bd167359.png)
[错误内容.txt](https://github.com/dotnetcore/Natasha/files/8429295/default.txt)

**Comment by NMSAzulX** [comment]
@hyzx86  引用正式版 `DotNetCore.Natasha.CSharp`     预热代码: `NatashaInitializer.Preheating();`

**Comment by hyzx86** [comment]
> @hyzx86 引用正式版 `DotNetCore.Natasha.CSharp` 预热代码: `NatashaInitializer.Preheating();`

好的 大帅，已经降级到 4.0.0-alpha.1 版本 没问题了。
正式版在.net 6 下的 OrchardCore 里面 存在 分析项冲突，提示让我升级什么 Microsoft.xxx Analysis包

Natasha 贼棒！

![image](https://user-images.githubusercontent.com/15613121/162134517-4a27ef0d-e9d4-4b2a-b872-fe48570ee8f1.png)

**Comment by NMSAzulX** [comment]
正式版本有4.0.0.1 版本 和 4.1.0.0 版本, 今天升级了 4.1.0.0 版本, 是最新的 Analysis 包.

**Comment by hyzx86** [comment]
嗯。。暂时还没刷出来
![image](https://user-images.githubusercontent.com/15613121/162157169-6dc5f8db-e83c-45fe-bc66-1ba08bdc438a.png)

**Comment by hyzx86** [comment]
> 这个是老版本的, 新版名字是: DotNetCore.Natasha.CSharp

好得

**Comment by hyzx86** [comment]
升级到 4.1.0了
` <PackageReference Include="DotNetCore.Natasha.CSharp" Version="4.1.0" />`
很奇怪。。测试代码单独跑没问题，
加到其他项目就不行了~
![image](https://user-images.githubusercontent.com/15613121/162259941-5809e34d-0b85-4e8b-bb87-86aadb39b3c6.png)
![image](https://user-images.githubusercontent.com/15613121/162260029-3b7a4407-354a-44b2-b2b0-537d25cdb586.png)

**Comment by NMSAzulX** [comment]
可能是你正式项目没引用正确的包, 或者编译器的编码的问题.

**Comment by hyzx86** [comment]
恩。。下面这个目前运行良好~
`<PackageReference Include="DotNetCore.Natasha.CSharp.All" Version="4.0.0-alpha.1" />`

**Comment by NMSAzulX** [comment]
可以通知 OrchardCore  升级依赖, 建议用最新依赖.

**Comment by hyzx86** [comment]
> 可以通知 OrchardCore 升级依赖, 建议用最新依赖.

依赖 是指分析包么？

**Comment by hyzx86** [comment]
@NMSAzulX  大佬，升级哪个依赖哦。。。麻烦明确下谢谢
