### ISSUE TITLE
第一次动态编译慢

### ISSUE THREAD

**Issue by 812169562** [dotnetcore/Natasha#13]
用了DelegateOperator.CreateUsingStrings 进行动态构建调用一个方法，发现是每次第一次动态构建的时候都非常慢。

**Comment by NMSAzulX** [comment]
@812169562 用的是2.0预览版吗？ 如果方便的话可以提供几行代码😁

**Comment by NMSAzulX** [comment]
第一次加载包括很多静态构造过程，Natasha很多初始化是由静态初始化触发的，真正的编译耗时大概在0.几秒，所以程序运行起来之后的第一次编译会很慢，这个没办法改进，**你可以在使用之前用一次编译进行预热**。

**Comment by 812169562** [comment]
不是预览版，我想应该是我里面引用包太多，我还是通过第一次编译预热了，运行时再弄确实慢。谢谢。
