### ISSUE TITLE
NDelegate.Action发生异常！提示参数arg1不存在。

### ISSUE THREAD

**Issue by yyylly** [dotnetcore/Natasha#130]
前置条件：
.Net6.0.100
DotNetCore.Natasha.CSharp (4.2.0) 
DotNetCore.Compile.Environment (3.0.0)

发生异常！提示当前上下文中不存在名称arg1。
`NDelegate.CreateDomain("TestCustomDelegate").Action<string>("Console.WriteLine(arg1);").Invoke("我是谁？");`
执行正常。
` NDelegate.CreateDomain("TestCustomDelegate").Action<string,string>("Console.WriteLine(arg1+\"-\"+arg2);").Invoke("我是谁？","我是靓仔");`

**Comment by sidrong** [comment]
我反编译生成的dll看到，如果只有一个参数的，参数名是obj，如果是两个及以上参数，参数名arg1, arg2.....

**Comment by NMSAzulX** [comment]
@sidrong @sidrong  F12看系统对 Action和Func的定义代码.

**Comment by NMSAzulX** [comment]
参数名是系统委托的反射结果

**Comment by yyylly** [comment]
get
