### ISSUE TITLE
新版本里不支持.NET Framework或.NET Standard？

### ISSUE THREAD

**Issue by emako** [dotnetcore/Natasha#136]
如题

**Comment by NMSAzulX** [comment]
暂不支持, 需要重写 [NatashaDomain](https://github.com/dotnetcore/Natasha/blob/main/src/Natasha.Domain/Core/NatashaDomain.cs#L11) , ALC 是 Core 时代的程序集隔离实现.

**Comment by NMSAzulX** [comment]
可以提交PR 兼容 .NET Framework,  .NET Standard 缺少运行时API ,  需要很多兼容代码, 所以换成具体版本了.

**Comment by emako** [comment]
那兼容确实有点难，还是用Roslyn实现好了。
