### ISSUE TITLE
hello world 失败

### ISSUE THREAD

**Issue by gitlsl** [dotnetcore/Natasha#147]
https://natasha.dotnetcore.xyz/zh-Hans/docs/get_started/getting-started  
按这里所说 跑不起来  得到异常 
`找不到 RuntimeMetadataVersion 的值。找不到包含 System.Object 的程序集，或未通过选项为 RuntimeMetadataVersion 指定值。`

我的代码    .net core 6
````
NatashaManagement.Preheating();
//你需要准备一个字符串
string script = "Console.WriteLine(\"Hello World!\");";
for (int i = 0; i < 10; i++)
{
    //      NDomain.Random().Delegate(script);  这个类没了    NatashaManagement.CreateRandomDomain() 没有 Action方法?.
    var action = NDelegate.RandomDomain().Action(script);
    action();
    //如果以后都不会再用 action 可以卸载
    action.DisposeDomain();
}
````

**Comment by suiye007** [comment]
我的也没有一个能跑起来的

**Comment by NMSAzulX** [comment]
https://natasha.dotnetcore.xyz/zh-Hans/docs/get_started/getting-started(发布有延迟)
https://natasha.dotnetcore.xyz/zh-Hans/docs/get_started/samples(可用)
https://github.com/dotnetcore/Natasha/blob/dev/samples/Sample3/Program.cs(可用)

**Comment by NMSAzulX** [comment]
> https://natasha.dotnetcore.xyz/zh-Hans/docs/get_started/getting-started 按这里所说 跑不起来 得到异常 `找不到 RuntimeMetadataVersion 的值。找不到包含 System.Object 的程序集，或未通过选项为 RuntimeMetadataVersion 指定值。`
> 
> 我的代码 .net core 6
> 
> ```
> NatashaManagement.Preheating();
> //你需要准备一个字符串
> string script = "Console.WriteLine(\"Hello World!\");";
> for (int i = 0; i < 10; i++)
> {
>     //      NDomain.Random().Delegate(script);  这个类没了    NatashaManagement.CreateRandomDomain() 没有 Action方法?.
>     var action = NDelegate.RandomDomain().Action(script);
>     action();
>     //如果以后都不会再用 action 可以卸载
>     action.DisposeDomain();
> }
> ```

文档有讲, 缺乏环境需要额外引入环境包.

**Comment by suiye007** [comment]
我的是一直报没有引用'net.... 'DLL，用官方的方法直接编译通过了

**Comment by NMSAzulX** [comment]
@suiye007  DotNetCore.Compile.Environment

**Comment by Ramon403** [comment]
> @suiye007 DotNetCore.Compile.Environment

引用了也是一样的

**Comment by NMSAzulX** [comment]
@Ramon403  看下你的代码和报错.

**Comment by NMSAzulX** [comment]
@Ramon403 @suiye007 @gitlsl  这里沟通太慢了 急得话加微信群解决

**Comment by Ramon403** [comment]
应该是环境的问题，但是不知道需要安装啥，所以最好直接在nuget安装全量包  .ALL 结尾的那个就搞定了
