### ISSUE TITLE
你好，有没有升级到dotnet6的计划，我遇到了版本冲突

### ISSUE THREAD

**Issue by zhangzw218** [dotnetcore/Natasha#155]
大概的冲突代码如下：

`	严重性	代码	说明	项目	文件	行	禁止显示状态 错误	
	NU1107	Microsoft.CodeAnalysis.Common 中检测到版本冲突。直接安装/引用 Microsoft.CodeAnalysis.Common 4.0.0 到项目  可解决此问题。 
 Volo.Abp.AspNetCore.Mvc 5.3.4 -> Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation 6.0.5 -> Microsoft.CodeAnalysis.Razor 6.0.5 -> Microsoft.CodeAnalysis.Common (>= 4.0.0) 
 
 DotNetCore.Natasha.CSharp.All 3.6.0 -> DotNetCore.Natasha.CSharp.Template 3.6.0 -> DotNetCore.Natasha.CSharp.Engine 3.6.0 -> Microsoft.CodeAnalysis.CSharp.Workspaces 3.11.0 -> Microsoft.CodeAnalysis.Common (= 3.11.0).	FJMarket.QuestionMiniProgram.InterfaceWeb	`

我尝试通过安装更高版本解决问题，但遇到了新的错误：
 Unable to load one or more of the requested types.
Method 'get_MetadataToken' in type 'Microsoft.CodeAnalysis.CodeGeneration.CodeGenerationArrayTypeSymbol' from assembly 'Microsoft.CodeAnalysis.Workspaces, Version=3.11.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
想知道，你们有没有更新到net6的计划？

**Comment by NMSAzulX** [comment]
支持 NET6 , 这个错误是依赖库的版本错误吧

**Comment by NMSAzulX** [comment]
DotNetCore.Natasha.CSharp  使用最新版

**Comment by NMSAzulX** [comment]
DotNetCore.Natasha.CSharp.All 是老架构版本了, 现在不更新了.
