### ISSUE TITLE
[Feature]: 希望AssemblyCSharpBuilder对象能添加任何时候，只Builder一个Assembly。

### ISSUE THREAD

**Issue by RemMai** [dotnetcore/Natasha#174]
### 📞 您的联系方式(Contact Details).

remmai@remmai.com

### 💢 描述一下你的烦恼 (Is your feature request related to a problem? Please describe).

AssemblyCSharpBuilder是一个强大Assembly拓展类
但是在我的使用 AssemblyCSharpBuilder 的时候发现很多反射方法 如果已经使用了 GetAssembly再去使用GetDelegateFromFullName，就会出现异常。

查看源码发现 都会去调用GetAssembly，GetAssembly函数内部会去Builer一个新的程序集，而且在builder第二个的时候，会出现异常，也就复现了上诉问题。

### 💡 描述一下你理想中的解决方案 (Describe the solution you'd like).

设置个方法让 AssemblyCSharpBuilder 生成的 Assembly 是单例模式。

**Comment by NMSAzulX** [comment]
https://github.com/dotnetcore/Natasha/commit/94016dc74c32e616e806fc7322b0a1d659612e84
