### ISSUE TITLE
[Feature]: AssemblyCSharpBuilder可以追加编译到同一个Assembly

### ISSUE THREAD

**Issue by DonPangPang** [dotnetcore/Natasha#177]
### 📞 您的联系方式(Contact Details).

powertle@outlook.com

### 💢 描述一下你的烦恼 (Is your feature request related to a problem? Please describe).

结合场景，如果有一个项目，支持输入脚本动态编译，那么每次对于脚本的Commit最后都会变为一个Assembly，即使他们在逻辑上应该是在一起的。

### 💡 描述一下你理想中的解决方案 (Describe the solution you'd like).

如果能够追加到同一个Assembly，或者合并Assembly，可以降低缓存的维度🤔使用起来也更加方便

**Comment by WeihanLi** [comment]
能不能从之前编译的 domain 里获取到 compilation 相关的语法树，从而与新的代码进行合并，但是合并后编译可能需要一个新的 domain，不然可能会有冲突，不知道能不能接受一个新的 domain，原来的 domain 可能不一定能及时销毁

如果不能接受新的 domain 的话，感觉可能还是用户自己把要编译好的代码组成到一起延迟编译会比较好

**Comment by DonPangPang** [comment]
例如一个脚本驱动的系统，启动时需要加载历史存储的脚本，当然，也可以通过系统新增脚本，然后业务由脚本完成。

目前的使用就是一个脚本会对应一个Assembly，当然，加载历史脚本时可以进行合并，但是对于新增的来说，就无法达到预期的效果。在这个系统中，由于脚本的体量可能是庞大的，通过Domain的划分可能比较笼统，所以我设想是不是可以将一些脚本追加到同一个Assembly中。

**Comment by WeihanLi** [comment]
感觉这个需求可以考虑尝试 roslyn 的 scripting 功能，natasha 也可以考虑增加/扩展 scripting 的支持

``` csharp
var state = await CSharpScript.RunAsync("int x = 1;");
state = await state.ContinueWithAsync("int y = 2;");
state = await state.ContinueWithAsync("x+y");
Console.WriteLine(state.ReturnValue);
```

https://github.com/dotnet/roslyn/blob/main/docs/wiki/Scripting-API-Samples.md#-continue-script-execution-from-a-previous-state

**Comment by NMSAzulX** [comment]
> 能不能从之前编译的 domain 里获取到 compilation 相关的语法树，从而与新的代码进行合并，但是合并后编译可能需要一个新的 domain，不然可能会有冲突，不知道能不能接受一个新的 domain，原来的 domain 可能不一定能及时销毁
> 
> 如果不能接受新的 domain 的话，感觉可能还是用户自己把要编译好的代码组成到一起延迟编译会比较好

增加了API, 可以返回一个格式化好的未编译的 Compilation,  也是编译用的 Compilation,  可以返回给用户.
提交记录:  https://github.com/dotnetcore/Natasha/commit/62bb4ffcb9b18fbeb096808dd010f0e2517891a6




> 感觉这个需求可以考虑尝试 roslyn 的 scripting 功能，natasha 也可以考虑增加/扩展 scripting 的支持
> 
> ```cs
> var state = await CSharpScript.RunAsync("int x = 1;");
> state = await state.ContinueWithAsync("int y = 2;");
> state = await state.ContinueWithAsync("x+y");
> Console.WriteLine(state.ReturnValue);
> ```
> 
> https://github.com/dotnet/roslyn/blob/main/docs/wiki/Scripting-API-Samples.md#-continue-script-execution-from-a-previous-state

这一点我感觉是轻量化的需求, 轻量化确实可以考虑一手...

**Comment by NMSAzulX** [comment]
> 例如一个脚本驱动的系统，启动时需要加载历史存储的脚本，当然，也可以通过系统新增脚本，然后业务由脚本完成。
> 
> 目前的使用就是一个脚本会对应一个Assembly，当然，加载历史脚本时可以进行合并，但是对于新增的来说，就无法达到预期的效果。在这个系统中，由于脚本的体量可能是庞大的，通过Domain的划分可能比较笼统，所以我设想是不是可以将一些脚本追加到同一个Assembly中。

只能创建新的程序集.  而且目前 API 也可以做.
同一个域追加程序集可能出现问题,  同命名空间同名类可能会引发异常.

**这是应用级别的需求, Natasha 无法提供底层支持.**

**Comment by DonPangPang** [comment]
> > 能不能从之前编译的 domain 里获取到 compilation 相关的语法树，从而与新的代码进行合并，但是合并后编译可能需要一个新的 domain，不然可能会有冲突，不知道能不能接受一个新的 domain，原来的 domain 可能不一定能及时销毁
> > 如果不能接受新的 domain 的话，感觉可能还是用户自己把要编译好的代码组成到一起延迟编译会比较好
> 
> 增加了API, 可以返回一个格式化好的未编译的 Compilation, 也是编译用的 Compilation, 可以返回给用户. 提交记录: [62bb4ff](https://github.com/dotnetcore/Natasha/commit/62bb4ffcb9b18fbeb096808dd010f0e2517891a6)
> 
> > 感觉这个需求可以考虑尝试 roslyn 的 scripting 功能，natasha 也可以考虑增加/扩展 scripting 的支持
> > ```cs
> > var state = await CSharpScript.RunAsync("int x = 1;");
> > state = await state.ContinueWithAsync("int y = 2;");
> > state = await state.ContinueWithAsync("x+y");
> > Console.WriteLine(state.ReturnValue);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > https://github.com/dotnet/roslyn/blob/main/docs/wiki/Scripting-API-Samples.md#-continue-script-execution-from-a-previous-state
> 
> 这一点我感觉是轻量化的需求, 轻量化确实可以考虑一手...

我们的应用设计就是脚本驱动，一个脚本可能非常庞大，由一个类或者多个类填充，例如登录功能，我们的基座上只支持了编译、调用和校验，逻辑全在脚本里😂😂而且开发一个业务相关的脚本时可能需要频繁修改。。
