### ISSUE TITLE
[Feature]: 预热机制改进

### ISSUE THREAD

**Issue by DonPangPang** [dotnetcore/Natasha#179]
### 📞 您的联系方式(Contact Details).

powertle@outlook.com

### 💢 描述一下你的烦恼 (Is your feature request related to a problem? Please describe).

现在的预热机制是直接拿所有的dll，然后再筛选掉不需要的，如果某些dll本来就是错误的，或者是拿不到的，就会导致Natasha预热失效，从而影响到整个业务。

### 💡 描述一下你理想中的解决方案 (Describe the solution you'd like).

应该可以预先设置一个黑名单之类的机制，直接让Natasha跳过某些dll的读取，并且在预热读取dll的时候，如果出现读取错误，也不应直接中断，应该写入日志，并继续预热其它dll

**Comment by NMSAzulX** [comment]
Same with : https://github.com/dotnetcore/Natasha/issues/178
