### ISSUE TITLE
可序列化的抽象表达式

### ISSUE THREAD

**Issue by liuhaoyang** [dotnetcore/Natasha#2]
在分布式应用中，遇到在client编写函数，通过特定机制允许client函数可以在不同server节点中远程执行的需求。
基于此需求，natasha是否支持构造可序列化的IL抽象表达式，允许在远端解析此表达式从而动态构造可执行函数？

**Comment by NMSAzulX** [comment]
@liuhaoyang   

新版Natasha已经实现了一版远程调用功能。有如下限制：

1. 只有带返回值的远程函数可以被调用。
2. 采用Json.net序列化方式。  
  
#### 案例如下：
-----------------------

**Model:**
```C#
public class RemoteTestModel
    {
        public void Say()
        {
            Console.WriteLine("hello world");
        }

        public string Hello(string str1,string str2)
        {
            return str1 + str2;
        }
    }
```
----------------------
**Client:**
```C#
var parameter =new ParametersMaker<RemoteTestModel>();
var remoteParameters = parameter["Hello"].Params("hello ","world!");
Request(remoteParameters );
```

----------------------
**Server:**
```C#
//预先封装被远程调用的类
RemoteWritter.ComplieToRemote<RemoteTestModel>();

//来自客户端
var parameters = Request.Parameters;
string result = RemoteReader.Invoke(parameters);
//字符串结果/或者其他非字符串的序列化结果
Response(result);
```
已经上了UT测试，Bechmark等待下一版，详见 [https://github.com/dotnet/BenchmarkDotNet/issues/1152#issuecomment-494178544](https://github.com/dotnet/BenchmarkDotNet/issues/1152#issuecomment-494178544)

**Comment by NMSAzulX** [comment]
@liuhaoyang 

客户端可以推字符串给服务端

服务端使用即可在内存生成远程调用封装，调用方法如上即可。
```C#
RemoteBuilder.Script = Request.Msg;
```
