### ISSUE TITLE
在netcore3.1的aspnetcore项目里跑不起来啊。

### ISSUE THREAD

**Issue by wang2650** [dotnetcore/Natasha#24]
1 通过nuget引用的方式
   <TargetFramework>netcoreapp3.1</TargetFramework>
    <PreserveCompilationContext>true</PreserveCompilationContext>
    <MvcRazorExcludeRefAssembliesFromPublish>false</MvcRazorExcludeRefAssembliesFromPublish>
这个也加了。  报Microsoft.AspNetCore.Antiforgery.dll找不到.

2 直接在您的项目的源码里，新建webapi项目。则直接报natasha的2.8.11 的ll找不到。

**Comment by wang2650** [comment]
![image](https://user-images.githubusercontent.com/3048544/71653246-643f3700-2d66-11ea-8d18-93034bacd17f.png)
在netcoreweb项目的controller里直接调用

**Comment by wang2650** [comment]
netcore webapi的controller里
  [HttpGet]
        public IEnumerable<WeatherForecast> Get()
        {
            var func = NDomain.Create("NDomain1").Func<string>("return \" 王!\";");
            var result = func();
            func.DisposeDomain();
到 var func = NDomain.Create("NDomain1").Func<string>("return \" 王!\";"); 这句直接报下面的错误


InvalidOperationException: Cannot find reference assembly 'Microsoft.AspNetCore.Antiforgery.dll' file for package Microsoft.AspNetCore.Antiforgery.Reference

**Comment by NMSAzulX** [comment]
@wang2650  十分感谢你的issue；
如下两个解决方案：

方案1：
引用 `Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation` 包，使用Razor的编译服务。

方案2：
在工程文件内添加节点：
`<PreserveCompilationReferences>true</PreserveCompilationReferences>`

如下：
```C#
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <PreserveCompilationReferences>true</PreserveCompilationReferences>
  </PropertyGroup>
```

很抱歉，Web方面照顾不周。
