### ISSUE TITLE
[Bug]: preparing报错

### ISSUE THREAD

**Issue by yan122725529** [dotnetcore/Natasha#247]
### ⚙️ OS

Windows (Default)

### ⚙️ Architecture

x64

### ⚙️ .NET Version

.NET7(STS)

### 📄 请描述您的问题(Describe the bug).

![image](https://github.com/dotnetcore/Natasha/assets/9899295/6fab0687-0fc2-4f3f-9201-c3b656be9589)
报错

![image](https://github.com/dotnetcore/Natasha/assets/9899295/7b61c6b5-d0f5-4992-876c-772248906cb6)
应该是这段代码导致

### ⭕ BUG 重现(To Reproduce).

必现

### 📞 您的联系方式(Contact Details).

mr.yanzhengyu@hotmail.com

**Comment by NMSAzulX** [comment]
未检测到合适的 ISSUE 推荐给您。感谢您的反馈！
> 该条自动推荐信息来自于 nms-bot.

**Comment by NMSAzulX** [comment]
@yan122725529 这里确实存在问题，A 写入共享域中了，如果你在其他域也创建一个 A 那可能会出现问题。 

目前解决方案是最好暂时避开 A 命名结构类的代码。

> 1月初会发布新版本，不仅修复此问题，还支持轻量级编译(不受预热影响)，我正在写文档。同时如果感兴趣可以参与一下 ISSUE 讨论 [轻量编译计划](#210)  和 [动态方法使用率统计](#240)

**Comment by yan122725529** [comment]
收到，期待新版本更新
