### ISSUE TITLE
有一个小需求请教下

### ISSUE THREAD

**Issue by MonkSoul** [dotnetcore/Natasha#27]
非常感谢您提供这么好的库！

现在我有一个需求，我想按照某个类的样子动态创建一个影子类，也就是类结构一模一样，但是 不是同一个类。(特别说明不是拷贝对象的意思)，我想动态创建影子类放到动态创建的程序集中，程序启动时注入到应用中。

看起来有点像代理类。之前想通过castle.core做，但是没达到预想。

**Comment by NMSAzulX** [comment]
可以的， 旧版可以直接用 AssemblyComplier 操作类直接编译字符串，新版发布（预计4月20）后将改为 AssemblyBuilder .  通过 Add 方法添加字符串，通过Compile方法编译，也可以通过 NClass 操作类来定制类模板，然后获取类型。

做代理的话是比较容易的，https://github.com/night-moon-studio/DynamicProxy  这个库就是实现了方法代理。

**Comment by MonkSoul** [comment]
感谢，已经知道怎么做了！
