### ISSUE TITLE
[Bug]: readme中的文档地址是错误。

### ISSUE THREAD

**Issue by player95** [dotnetcore/Natasha#270]
### ⚙️ OS

None

### ⚙️ Architecture

Any (Default)

### ⚙️ .NET Version

.NET8(LTS) (Default)

### 📄 请描述您的问题(Describe the bug).

readme中的文档地址是错误。打不开。

**Comment by NMSAzulX** [comment]
未检测到合适的 ISSUE 推荐给您。感谢您的反馈！
> 该条自动推荐信息来自于 nms-bot.

**Comment by NMSAzulX** [comment]
@player95 感谢 已修复
