### ISSUE TITLE
学习这个需要哪些必备知识

### ISSUE THREAD

**Issue by bxjg1987** [dotnetcore/Natasha#29]
对.net动态部分只熟悉反射 dynamic 之类的，要使用这个库有没有一个必备知识列表，我想深入学习下这个库

**Comment by NMSAzulX** [comment]
你好：

- 要了解域、程序集、类型、方法/属性/字段它们之间的关系；
- 域是大量动态构建的隔离容器，你需要在所有操作之前，最先考虑它的存在，尤其特别是你在做插件开发时，具体操作可参见文档。
- Natasha 注重 C# 语法你需要遵从 C# 的语法来构建动态的需求；
- 可以用模板 NClass / NInterface / NEnum / NStruct 来构建动态需求。
- 也可以直接传字符串到 AassemblyCSharpBuilder 来构建你的需求，详细可参见文档。
- using 是你需要特别注意的地方， Natasha 默认启用添加所有 Using, 也可以使用 CustomUsing 方法来切换到自定义的 Using.
- Natasha 初衷是为了替代 Emit，所以如果你有 Expression 或 Emit 的编程基础，想必可以迅速上手；
- 当你使用该库进行高级且复杂的封装时，你要清楚，这项技术带来的配置维度要比目前市面所有的类库配置维度要多。
- Natasha 周边有 R2D / DynamicCache 可以为你的类库及代码提供性能加速。
- 及时反馈你的问题，我可以尽快回复。

**Comment by NMSAzulX** [comment]
虽然 dynamic 已经提升了性能，但不及 NMS.NCaller 的性能，动态构建的性能十分给力，欢迎使用。

**Comment by bxjg1987** [comment]
@NMSAzulX 非常感谢哈~对程序域、程序集、Emit Expression有一些了解。我们公司是做医疗软件的，要求非常灵活，我在想用这个动态库可以做到非常灵活。等把.net core知识补充熟悉了 再来继续研究这个库~   感谢~哈

**Comment by NMSAzulX** [comment]
没问题，我觉得这是一个生态的起点，一起加油。
