### ISSUE TITLE
[Feature]: 减少预热产生的内存占用

### ISSUE THREAD

**Issue by xiaolipro** [dotnetcore/Natasha#302]
### 💢 描述一下你的烦恼 (Is your feature request related to a problem? Please describe).

![882f7cf50eb207bc8dcbd8f6645be8b](https://github.com/dotnetcore/Natasha/assets/49677180/74c2f087-5377-4509-9247-bc692c201e36)
预热一开，生成了大量重复的命名空间。我希望继续使用无须手写using的特性，但不想承担如此大的内存开销。

### 💡 描述一下你理想中的解决方案 (Describe the solution you'd like).

让builder不断学习它所在业务场景用到的using

### ❌ 描述一下你已经使用过或者考虑过的其他方案 (Describe alternatives you've considered).

经过讨论，没有剪裁的可能

### 🍺 附加信息 (Additional context).

![image](https://github.com/dotnetcore/Natasha/assets/49677180/6ad0fae5-0367-4bda-b6ab-8191d7ee2564)

**Comment by NMSAzulX** [comment]
|编号|相似度|ISSUE|
| :----: | :----: | :---------- |
|1|72.17%| [[Feature]: 下一版本优化内存占用问题,进一步减少内存占用.](https://github.com/dotnetcore/Natasha/issues/196) |

> 该条自动推荐信息来自于 nms-bot.
