### ISSUE TITLE
[建议]推荐构建一个表达式执行引擎示例

### ISSUE THREAD

**Issue by Cloud33** [dotnetcore/Natasha#34]
看了一下特性，感觉比较合适做表达式执行引擎，类似于`Aviator`，关注高性能，注意`GC`，这样一个示例项目才能展现`Natasha`的利害之处啊😍

**Comment by xljiulang** [comment]
先做表示式的Parser，后期加表达式的序列化

**Comment by Cloud33** [comment]
嗯，可以慢慢做，现在感觉直接使用`Natasha`做东西还是有点底层了，也不知道做什么东西，在什么场景下使用，感觉规则这块比较合适它，因为它是一个动态的；这个项目还是非常有潜力的，超级棒👍👍👍

**Comment by NMSAzulX** [comment]
是的，目前有人在做 NatashaPad : https://github.com/night-moon-studio/NatashaPad     
大多市面上类库都可以被 Natasha 翻新， 非常复杂的动态构建 Natasha 做起来非常合适。
除了封装，框架，业务都非常有优势，哈哈。
