### ISSUE TITLE
将 Readme.md 的内容 翻译并覆盖到对应的 英文 readme 当中

### ISSUE THREAD

**Issue by newbe36524** [dotnetcore/Natasha#357]
// 体验 github copilot workspace

**Comment by NMSAzulX** [comment]
未检测到合适的 ISSUE 推荐给您。感谢您的反馈！
> 该条自动推荐信息来自于 nms-bot.

**Comment by NMSAzulX** [comment]
OK.  PR 内容是由 github copilot workspace 生成的？

**Comment by NMSAzulX** [comment]
#358 已合并。

**Comment by newbe36524** [comment]
> OK. PR 内容是由 github copilot workspace 生成的？

对的呢，只有 issue 是自己写的，别的都是生成的。可以申请试试看。
