### ISSUE TITLE
动态脚本,如何和宿主程序中的对象交互

### ISSUE THREAD

**Issue by donghuali110** [dotnetcore/Natasha#37]
public class Globals{ publicintX; publicintY;}
varglobals = newGlobals { X = 1, Y = 2};
Console.WriteLine(awaitCSharp.EvaluateAsync< int>( "X+Y", globals: globals));
如上,使用roslyn脚本中可以访问宿主程序中的对象,
那么使用natasha该如何实现呢,谢谢~

**Comment by NMSAzulX** [comment]
@donghuali110  

如果是普通的调用，比如 MyStaticClass.Name 这种静态类可以在脚本中直接写，如果不是静态的，是局部变量或者其他可以参考 ： https://github.com/night-moon-studio/RuntimeToDynamic 这个项目。 
这个项目的做法是代理，将运行时的数据代理到静态类或者普通类中。
首先构建一个类或者静态类，这个类包含接收运行时数据的字段，同时包含一个方法，接收外部的数据，在方法内部对字段进行赋值存储，之后再通过脚本调用。

**Comment by NMSAzulX** [comment]
@donghuali110  针对上面的例子 可以
```C#
var func = NDelegate.RandomDomain().Func<Gloabls>("return arg.X+arg.Y;"); 
func(globals);
```

**Comment by donghuali110** [comment]
@NMSAzulX 多谢回复. Natasha是一个很优秀的项目,解决了困扰我多时的动态编译内存泄漏问题.会持续关注这个项目的~

**Comment by NMSAzulX** [comment]
@donghuali110 加油，希望以后有机会能一起维护这个项目。
