### ISSUE TITLE
有办法实现动态控制器并路由吗？

### ISSUE THREAD

**Issue by qcjxberin** [dotnetcore/Natasha#38]
有办法实现动态控制器并路由吗？

**Comment by NMSAzulX** [comment]
https://github.com/dotnetcore/Natasha/blob/master/samples/Core31WebApi/Controllers/NatashaController.cs#L26

**Comment by qcjxberin** [comment]
我的意思是控制器本身也是动态的.

**Comment by NMSAzulX** [comment]
控制器可以是动态的，你生成控制器类之后注册进去就行了。

**Comment by NMSAzulX** [comment]
首页的动图就是展示的这个操作，如果打不开需要自己改一下HOST

**Comment by qcjxberin** [comment]
首页的动态那效果有DEMO代码吗？

**Comment by NMSAzulX** [comment]
就是我发的那个链接，是 core31WebAPi 项目

**Comment by qcjxberin** [comment]
好的，谢谢

**Comment by qcjxberin** [comment]
你给的Demo好像没有用//仅仅注册组件
NatashaInitializer.Initialize();
//注册+预热组件 , 之后编译会更加快速
await NatashaInitializer.InitializeAndPreheating();这些来预热的

**Comment by qcjxberin** [comment]
另外这种方式能用在mvc上吗？

**Comment by NMSAzulX** [comment]
> 你给的Demo好像没有用//仅仅注册组件
> NatashaInitializer.Initialize();
> //注册+预热组件 , 之后编译会更加快速
> await NatashaInitializer.InitializeAndPreheating();这些来预热的

使用最新版 Natasha 例子没有更新。

MVC 上没做过调研，理论上可以使用。因为 MVC 组件要比 API 组件要多。

**Comment by NMSAzulX** [comment]
![image](https://user-images.githubusercontent.com/16236903/97135024-175f9d80-178a-11eb-9162-12f545828b54.png)
用 
NatashaInitializer.InitializeAndPreheating(); 代替下面3句。

**Comment by qcjxberin** [comment]
我先试下看看

**Comment by qcjxberin** [comment]
如果有使用Autofac的话，报错了
![image](https://user-images.githubusercontent.com/5792218/97149010-083b1880-17a7-11eb-84cb-df9a25b32c6f.png)

**Comment by NMSAzulX** [comment]
嗯，这个需要把注册的实例保留，在添加动态路由的时候再注册一下。

**Comment by qcjxberin** [comment]
具体应该怎么写代码的？

**Comment by NMSAzulX** [comment]
请提供更多的信息，startup.cs  和 TestController

**Comment by NMSAzulX** [comment]
程序代码可以打包发我邮箱 2765968624@qq.com

**Comment by qcjxberin** [comment]
TestController就是demo里的，其他的代码就是默认有使用autofac的这种，现在手上的项目框架太大了，不方便发。

**Comment by NMSAzulX** [comment]
嗯

**Comment by qcjxberin** [comment]
能解决了麻烦在这里回复一下。

**Comment by NMSAzulX** [comment]
这个属于 Autofac 的问题，如果您着急使用请先联系 Autofac 的团队询问。

**Comment by NMSAzulX** [comment]
> > https://github.com/dotnetcore/Natasha/blob/master/samples/Core31WebApi/Controllers/NatashaController.cs#L26
> 
> 这地址404了，请问webapi的示例项目还有吗

https://github.com/dotnetcore/Natasha/blob/Achive31/samples/Core31WebApi/Controllers/NatashaController.cs

**Comment by fory77** [comment]
> > > https://github.com/dotnetcore/Natasha/blob/master/samples/Core31WebApi/Controllers/NatashaController.cs#L26
> > 
> > 
> > 这地址404了，请问webapi的示例项目还有吗
> 
> https://github.com/dotnetcore/Natasha/blob/Achive31/samples/Core31WebApi/Controllers/NatashaController.cs

多谢张老师，不过，在新版里没有NatashaController，用什么替代呢？

**Comment by fory77** [comment]
> > > https://github.com/dotnetcore/Natasha/blob/master/samples/Core31WebApi/Controllers/NatashaController.cs#L26
> > 
> > 
> > 这地址404了，请问webapi的示例项目还有吗
> 
> https://github.com/dotnetcore/Natasha/blob/Achive31/samples/Core31WebApi/Controllers/NatashaController.cs

多谢张老师， 不过新版里貌似没有ScriptHelper,是有什么新的替代吗？还是需要我参考老版代码手动实现一下？我是.net6的项目

**Comment by NMSAzulX** [comment]
> > > > https://github.com/dotnetcore/Natasha/blob/master/samples/Core31WebApi/Controllers/NatashaController.cs#L26
> > > 
> > > 
> > > 这地址404了，请问webapi的示例项目还有吗
> > 
> > 
> > https://github.com/dotnetcore/Natasha/blob/Achive31/samples/Core31WebApi/Controllers/NatashaController.cs
> 
> 多谢张老师， 不过新版里貌似没有ScriptHelper,是有什么新的替代吗？还是需要我参考老版代码手动实现一下？我是.net6的项目

获取类名的工具类而已，自己实现一个就行，名字没有特殊用法，随便取。
