### ISSUE TITLE
这个项目的需求是什么?是要解决什么问题?

### ISSUE THREAD

**Issue by xiaolu6t** [dotnetcore/Natasha#40]
如果使用插件的话,那直接jekins编译就好了,为什么要用源码?
如果说是动态编译,直接用IL更方便快捷,且效率也高.
如果说是隔离工作,AppLoadContext也挺不错的.
我实在不明白这个项目的意义在哪里?

**Comment by NMSAzulX** [comment]
写着玩的，为了装逼。
