### ISSUE TITLE
同样的代码不能加载第二次AssemblyLoadContext is unloading or was already unloaded 

### ISSUE THREAD

**Issue by ananck** [dotnetcore/Natasha#49]
当用测试案例Core31WebApi测试的时候 同样的代码加载一次后执行没问题 然后删除,然后再加载会出现下面的错误 请问怎们解决
System.InvalidOperationException:“AssemblyLoadContext is unloading or was already unloaded.”

**Comment by NMSAzulX** [comment]
可能已经被 GC 移除了,  需要重复使用的程序集和方法不能删除.
