### ISSUE TITLE
有动态编译的文档或示例吗？

### ISSUE THREAD

**Issue by WeihanLi** [dotnetcore/Natasha#5]
有个使用 `CodeDom` 的项目，但是有个使用 dotnet cli 编译的问题 <https://github.com/aspnet/RoslynCodeDomProvider/issues/51> ，想试用一下 `Natasha` ，不知道是不是可以解决现在的问题，

有这样一个功能，根据源代码编译获取到一个Assembly，获取到里面定义的类型，可能需要支持引用指定的程序集，[项目代码](https://github.com/WeihanLi/DbTool/tree/e952ba83ca9a473a2ca8611583f5fd0cc237aede/src/DbTool/Utils.cs#L23)

``` csharp
        public static List<TableEntity> GeTableEntityFromSourceCode(params string[] sourceFilePaths)
        {
            if (sourceFilePaths == null || sourceFilePaths.Length <= 0)
            {
                return null;
            }
            var provider = new Microsoft.CodeDom.Providers.DotNetCompilerPlatform.CSharpCodeProvider();

            var result = provider.CompileAssemblyFromFile(new CompilerParameters(
                new[]
                {
                    "System.dll",
                    "System.ComponentModel.DataAnnotations.dll",
                }),
                sourceFilePaths);
            if (result.Errors.HasErrors)
            {
                var error = new StringBuilder(result.Errors.Count * 1024);
                for (var i = 0; i < result.Errors.Count; i++)
                {
                    error.AppendLine($"{result.Errors[i].FileName}({result.Errors[i].Line},{result.Errors[i].Column}):{result.Errors[i].ErrorText}");
                }
                throw new ArgumentException($"所选文件编译有错误{Environment.NewLine}{error}");
            }
            var types = result.CompiledAssembly.GetTypes();
            // ...
        }
```

**Comment by NMSAzulX** [comment]
@WeihanLi  只要是运行时的都可以编译，目前使用的语言版本是C# 7.3，在此基础上写的构造器。 详情代码请参考NatashaUT,  UT测试涵盖了大部分Natasha的功能。 动态编译类可以参照这里[整个类字符串](https://github.com/dotnetcore/Natasha/blob/master/NatashaUT/DynamicClassTest.cs) 、[构造器构建](https://github.com/dotnetcore/Natasha/blob/master/NatashaUT/DynamicBuilderTest.cs)，若调试，请在项目属性里打开DEBUG符号，默认在Debug文件夹里生成succeed.log 以及 error.log.

**Comment by NMSAzulX** [comment]
文档会写的慢一点，最近在做一些升级和优化，引擎架构已经稳定了。

**Comment by NMSAzulX** [comment]
@WeihanLi  <PreserveCompilationContext>true</PreserveCompilationContext>  这句话很重要，要在工程文件里加上，详细请看demo,  另外如果需要，Natasha可以发布一版Nuget. (仅支持standard2.0)

**Comment by WeihanLi** [comment]
👍  好的，现在项目还是 net45，我回头更新一下试一下
