### ISSUE TITLE
用asp.net core5 ，在action里生成dll文件，但这个文件一直被iis占用，怎么销毁

### ISSUE THREAD

**Issue by Godknow** [dotnetcore/Natasha#51]
用asp.net core5 ，在action里生成dll文件，但这个文件一直被iis占用，怎么销毁
试过这些，都不行。
            assembly.DisposeDomain();
            builder.Compiler.Domain.Remove(assembly);
            builder.Domain.Remove(assembly);
            builder.Domain.Remove(builder.OutputFolder+ @"\TestC.dll");
            builder.Domain.Unload();
            builder.Domain.Dispose();
            DomainManagement.Remove("TestC");

**Comment by NMSAzulX** [comment]
只能问问官方.

**Comment by NMSAzulX** [comment]
如果是动态编译的dll 可以选择使用流方式编译, 不生成dll.  如果是其他, 需要考虑 IIS 本身锁文件的情况.

**Comment by gitlsl** [comment]
这个问题  iis 在解决了，  net6正式版后  iis有配置设置为 不锁定 ，   直接ftp上传 会自动更新

**Comment by newbe36524** [comment]
> 这个问题 iis 在解决了， net6正式版后 iis有配置设置为 不锁定 ， 直接ftp上传 会自动更新

WOW 这居然有一个不锁定的新特性~

**Comment by NMSAzulX** [comment]
爱了爱了
