### ISSUE TITLE
Who is using Natasha？（欢迎使用 Natasha 的个人和公司在此留言）

### ISSUE THREAD

**Issue by NMSAzulX** [dotnetcore/Natasha#53]
## Who is using Natasha？
Sincerely thank everyone who constantly keeps on using and supporting Natasha. We will try our best to make Natasha better and make the community and ecology more prosperous.

## The original intention of this issue
 - We’d like to listen to the community to make Natasha better.
 - We want to attract more partners to contribute to Natasha.
 - Learn more about the practical use scenarios of Natasha to facilitate the next step of planning.
##  What we expect from you
Please submit a comment in this issue to include the following information:

your company, school or organization.
your city and country.
your contact info: blog, email, twitter (at least one).
for what business scenario do you use Natasha.

You can refer to the following sample answer:

> 
>Organization: nms
>Location: Beijing, China
>Contact: 1648107003@qq.com
>Purpose: Write open source class libraries based on Natasha.

Thanks again for your participation! Your support is the motivation for us to move forward.
NCC Natasha community

## 谁在使用 Natasha ？
感谢正在使用和关注 Natasha 的开发者，我们会持续投入，让 Natasha 项目和社区更加繁荣。

## 这个 issue 的出发点
 - 聆听社区的声音，让 Natasha  解决实际的问题
 - 吸引更多的开发者参与和贡献
 - 更多的了解 Natasha 的实际使用场景，以便后续版本的计划
## 我们期待您能提供
在此提交一条评论, 评论内容包括:

您所在公司、学校或组织
您所在的城市、国家
您的联系方式: 微博、邮箱、微信 (至少一个)
您将 Natasha 用于哪些业务场景

可以参考下面的示例：

> 
>组织：nms
>地点：中国北京
>联系方式： 1648107003@qq.com
>使用场景：基于 Natasha 打造开源项目.  

多谢您的支持！
NCC Natasha 社区

**Comment by zlzforever** [comment]
公司：上海林和草信息科技有限公司
地点：中国上海
联系方式： 136831898@qq.com
使用场景：基于 Natasha 打造地图服务

**Comment by wxzz** [comment]
公司：iNeuOS工业互联网操作系统
地点：中国北京
联系方式： 504547114@qq.com
使用场景：自定义脚本引擎
官方网站：http://www.ineuos.net

**Comment by gdlcf88** [comment]
组织：[EasyAbp](https://easyabp.io)
地点：GitHub
联系方式：47396430@qq.com
使用场景：实现 Entity UI 模块动态生成 RazorPages 的表单模型；实现 Dynamic Entity 模块的（开发者可于运行时在线编写的）业务逻辑脚本

**Comment by RemMai** [comment]
个人：RemMai
地点：中国深圳
联系方式： [remmai@remmai.com](mailto:remmai@remmai.com)
使用场景：编写CSharp脚本，实现接口，爬取图床的相关参数。
官方网站：http://remmai.com/

**Comment by zhiyangyou** [comment]
个人：zhiyangyou
地点：中国厦门
使用场景：在Unity的Editor中实时执行代码Clip，用于dump游戏的运行时数据。
