### ISSUE TITLE
支持从 Stream 加载 Assembly 依赖项

### ISSUE THREAD

**Issue by newbe36524** [dotnetcore/Natasha#55]
在 Blazor 环境中依赖项的 Assembly 无法以 File 的形式存在。因此需要从特定的 Stream 中加载 Assembly。
虽然我没看代码，但是我猜测现在必须从文件加载依赖项。
（手动滑稽）

这将有助于下一步为开发 Web 页面上可用的 Natasha 提供助力。

**Comment by NMSAzulX** [comment]
可以从流中加载， 这个流可以获取到吗？  `domain.LoadAssemblyFromStream( stream )`

**Comment by newbe36524** [comment]
Oh, 那看起来针布搓，应该是可以的。在 Blazor 下，可以将程序集通过 Http 流的方式返回。

**Comment by NMSAzulX** [comment]
OK
