### ISSUE TITLE
在maui.android项目中无法使用natasha

### ISSUE THREAD

**Issue by yiszza** [dotnetcore/Natasha#57]
![image](https://user-images.githubusercontent.com/42995476/131439055-a1d56063-7986-4226-83e0-68eb6cabbd8c.png)
只安装nuget包, 未进行调用

**Comment by NMSAzulX** [comment]
方便上传例子吗?

**Comment by yiszza** [comment]
> 方便上传例子吗?

已发送例子和复现视频至您的邮箱2765968624@qq.com

**Comment by NMSAzulX** [comment]
那个QQ 登录不上了, 您发到这里吧 1648107003@qq.com

**Comment by yiszza** [comment]
> 那个QQ 登录不上了, 您发到这里吧 [1648107003@qq.com](mailto:1648107003@qq.com)

好的, 已发送

**Comment by NMSAzulX** [comment]
首先来说 Natasha 暂未支持 .net6.0.  需要等到 .net 6 正试发布.

**Comment by yiszza** [comment]
> 首先来说 Natasha 暂未支持 .net6.0. 需要等到 .net 6 正试发布.

但natasha在.net6 控制台程序运行正常

**Comment by NMSAzulX** [comment]
嗯 应该是默认降到了 netstandard2.0 / net5.0 或者其他版本.

**Comment by yiszza** [comment]
> 嗯 应该是默认降到了 netstandard2.0 / net5.0 或者其他版本.

好的谢谢, 希望能早日支持.net6

**Comment by NMSAzulX** [comment]
@yiszza  会的, 感谢支持.
