### ISSUE TITLE
动态调用dll时会占用dll嘛？

### ISSUE THREAD

**Issue by jackletter** [dotnetcore/Natasha#6]
能否像IIS一样在程序部署后，在不停止服务器的情况下更新里面的dll文件

**Comment by NMSAzulX** [comment]
@jackletter  老铁抱歉，当初没有考虑到这方面的需求。

首先来说：动态编译的DLL文件会加入缓存，编译时会加载程序集，您的操作需要卸载程序集，这个操作原计划是在core 3.0中实现的。

7月份将做相关调研。

**Comment by jackletter** [comment]
期待这个功能，如果可以动态去插拔这些dll的话那系统部署后就很灵活了

**Comment by NMSAzulX** [comment]
@jackletter 感谢，另外推荐一下：https://github.com/dotnetcore/FlubuCore 这个项目，老铁可以调研一下。

**Comment by jackletter** [comment]
好的 已收藏

**Comment by NMSAzulX** [comment]
@jackletter 目前热更新工作已接近尾声，对于引用外部dll及其依赖项的支持仅在core3.0版本中实现，将在2.0.0-alpha.4 版本中做出对该功能的支持，文档还需稍后，感谢老铁关注。

**Comment by jackletter** [comment]
可以可以
