### ISSUE TITLE
Dynamic generate Does it support running on IOS & AOT

### ISSUE THREAD

**Issue by xlievo** [dotnetcore/Natasha#72]
Can dynamically generated proxy classes support AOT?

As far as I know, emit does not support AOT compilation!

**Comment by newbe36524** [comment]
I believe it doesn`t, just as expression tree does not supported IL compilation in IOS

**Comment by xlievo** [comment]
have you considered the use of reflection in AOT environment?

**Comment by newbe36524** [comment]
@eventhorizon-cli do you have any idea about this?

**Comment by xlievo** [comment]
thank you for your reply. I'll discuss it again if necessary...
