### ISSUE TITLE
 Natasha.Clone

### ISSUE THREAD

**Issue by duyanming** [dotnetcore/Natasha#8]
使用Natasha的克隆扩展:
Example:  

        Using : Natasha.Clone; 
        var instance = new ClassA();
        var result = instance.Clone();
![image](https://user-images.githubusercontent.com/17999146/62111203-aa3d2e00-b2e2-11e9-9781-62b5ef84118f.png)

        public static class CloneExtension
    {
        public static T Clone<T>(this T instance) where T : Delegate
        {
            return CloneOperator.Clone(instance);
        }
    }

 ClassA 这个为什么 是委托，不是类。看了这个名字好奇怪

**Comment by NMSAzulX** [comment]
@duyanming 感谢指正，Clone确实是全体类型的。
