### ISSUE TITLE
请问方法编译如何捕获编译异常呢？

### ISSUE THREAD

**Issue by wenjq0911** [dotnetcore/Natasha#9]
例如下面的代码，是段缺少分号的错误代码，在使用中如何捕获编译异常信息呢，现在编译失败只能判断action是null，并不能获得异常信息。
` 
var test_action = FastMethodOperator.New
                         .Param<object>("param")
                         .MethodBody("return param ")
                         .Return<object>()
                         .Complie<Func<object, object>>();

 test_action("hello");
`

**Comment by NMSAzulX** [comment]
@wenjq0911 
是的，目前操作就是判断是否为空，因为异常情况推荐的处理方法是，调试过程中解决错误日志出现的问题，保证程序运行之后不会有错误脚本生成。

后续会根据反馈的需求提供异常处理方法。

**Comment by NMSAzulX** [comment]
@wenjq0911 

v1.1.0.0将增加异常Model   
https://github.com/dotnetcore/Natasha/blob/master/src/Natasha/Engine/ExceptionModule/CompilationException.cs
  

编译末期捕获异常
https://github.com/dotnetcore/Natasha/commit/5d3f94f49e5c130f56e6bff78a8fc2786deb760a#diff-610fc37929f872a8daa84f7b62da5fe6  

UT测试
https://github.com/dotnetcore/Natasha/commit/5d3f94f49e5c130f56e6bff78a8fc2786deb760a#diff-2fa4469241ac311e81d77fd243ec1e41

感谢您的需求。
