### ISSUE TITLE
编译耗时较长

### ISSUE THREAD

**Issue by YBenX** [dotnetcore/Natasha#90]
![image](https://user-images.githubusercontent.com/3353434/144374809-fe5d1fda-80c5-418b-83de-8e0a39465a14.png)

**Comment by YBenX** [comment]
`var stopwatch = System.Diagnostics.Stopwatch.StartNew();
            stopwatch.Start(); 
            var delegateAction = FastMethodOperator.DefaultDomain() 
                        .Async()
                        .Param<string>("str1")
                        .Param<string>("str2")
                        .Body(@"
                            string a=""1"";
                            string b=""1"";  
                            return ""sss"";")
                        .Return<Task<string>>()

                .Compile();
            stopwatch.Stop();
            var totalMilliseconds = stopwatch.Elapsed.TotalMilliseconds;`

**Comment by NMSAzulX** [comment]
DotNetCore.Natasha.CSharp  beta2 版本:

![image](https://user-images.githubusercontent.com/16236903/149736949-4439ce85-fb86-4c7e-94f1-7e9473f35f20.png)

加载的引用:

![image](https://user-images.githubusercontent.com/16236903/149737186-cafa4691-ed33-4d99-9bac-ac2d5bf7ccf5.png)
